%YAML 1.2
---
laserScan:
    frame_id: rslidar
    angle_increment: 0.0174532923847
    time_increment: 0.0
    scan_time: 0.0329999998212
    range_min: 0.2
    range_max: 6.0

sonar_topics:
    - ultrasound_1
    - ultrasound_2
    - ultrasound_3
    - ultrasound_4
    - ultrasound_5
    - ultrasound_6

sonar_frames:
    - ultrasound_1
    - ultrasound_2
    - ultrasound_3
    - ultrasound_4
    - ultrasound_5
    - ultrasound_6

...
