%YAML 1.2
---
laserScan:
    frame_id: rslidar
    angle_increment: 0.0174532923847
    time_increment: 0.0
    scan_time: 0.0329999998212
    range_min: 0.649999976158
    range_max: 200.0

sonar_topics:
    - ultrasound1
    - ultrasound2
    - ultrasound3
    - ultrasound4
    - ultrasound5
    - ultrasound6

sonar_frames:
    - ultrasound1
    - ultrasound2
    - ultrasound3
    - ultrasound4
    - ultrasound5
    - ultrasound6

...
